### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by evertrol** [ajheaps/cf-plot#4]
Are there any plans to support Python 3 in the near future?

And with the upcoming API changes in CF-Python 3, will these be supported as well?

At the moment, I've forked the CF-Plot repository and converted the code as good as possible to Python 3 and the new CF-Python API, but as I'm not familiar with the CF-Plot code base, this attempt is likely lacking, and just a poor-man's attempt at providing support for some colleagues that want to try and use CF-Plot with Python 3.

**Comment by davidhassell** [comment]
cf-plot for Python 3 is being developed in parallel to cf-python v3, and the plan is to release both at the same time  - we're aiming for 1st October 2019.

David

**Comment by evertrol** [comment]
Thanks.
I hadn't seen any activity in this repository, which seemed in stark contrast to the development activity in the CF-Python repository. Hence my question.

**Comment by ajheaps** [comment]
I can let you have a pre-release cf-plot that I've converted over to Python 3 if you like.  If not we'll be doing a full release on 1st October as David says.

Regards
Andy

**Comment by evertrol** [comment]
That would be great.

I've mainly gone ahead and created my own version because I, or rather my colleagues using it, didn't want to wait (or revert back to Python 2). The problems arose when I ran into the new API that CF-Python 3 uses (as well as replacing some of the divisions, where it wasn't entirely clear if these should be integer divisions or floating point ones). 
I currently can get most examples on the (old) documentation to run, though not all (or not as well), which is my best testcase (having no unit tests or anything).

So a version to compare against would be nice.

**Comment by ajheaps** [comment]
My test version is available at http://www.met.reading.ac.uk/~swsheaps/cfplot.src3.tar

I'm modifying the code to separate out the colorbar code into a separate and independently callable routine.  This is ongoing work might give some issues but I'll pickup on this now that I'm back from holiday.

If you find any issues please email me at andy.heaps@ncas.ac.uk

**Comment by ajheaps** [comment]
Python 3 support has been in cf-plot for several years so I'll close this ticket now.
