### ISSUE TITLE
colorbar_position not working in 3.2.0

### ISSUE THREAD

**Issue by alaniwi** [ajheaps/cf-plot#8]
`colorbar_position` is broken (for some use cases at least) in 3.2.0

Test case:

data file `test.nc` attached (<1MB, but in a zip file because GitHub doesn't allow attaching .nc directly): [test.nc.zip](https://github.com/ajheaps/cf-plot/files/11020708/test.nc.zip)

**Broken example** (paths redacted in error message):

```
>>> import cf
>>> cf.__version__
'3.14.1'
>>> import cfplot as cfp
>>> cfp.__version__
'3.2.0'
>>> f=cf.read('test.nc')[1]
>>> f
<CF Field: eastward_wind(time(1), pressure(1), latitude(160), longitude(320)) m s**-1>
>>> cfp.con(f, colorbar_position=[0.1, 0.1, 0.8, 0.02])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/cfplot/cfplot.py", line 1029, in con
    cbar(labels=cbar_labels, orientation=cb_orient, position=colorbar_position,
  File "/path/to/cfplot/cfplot.py", line 8256, in cbar
    colorbar = matplotlib.colorbar.ColorbarBase(ax1, cmap=cmap,
UnboundLocalError: local variable 'ax1' referenced before assignment
```

**Working example** (same code, earlier `cfplot` version - also a different `cf` version but guessing that this is unimportant):

```
>>> import cf
>>> cf.__version__
'3.13.0'
>>> import cfplot as cfp
>>> cfp.__version__
'3.1.23'
>>> f=cf.read('test.nc')[1]
>>> f
<CF Field: eastward_wind(time(1), pressure(1), latitude(160), longitude(320)) m s**-1>
>>> cfp.con(f, colorbar_position=[0.1, 0.1, 0.8, 0.02])
>>> 
```
produces:
![image](https://user-images.githubusercontent.com/5577313/226405088-3b2f8fb5-13c3-467f-a7f8-9161a5422816.png)

**Comment by ajheaps** [comment]
Thanks for the bug report.  I had rewritten the cf-plot cbar routine somewhat and had a indent too far for the code related to the position option.  This is fixed in cf-plot 3.2.7
